# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_shoppingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='iteminfo',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='iteminfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.Ingredient'),
        ),
    ]
