# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fridge.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_auto_20181202_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_image', models.ImageField(upload_to='', verbose_name='menu_image')),
                ('main_ingredients', fridge.fields.JSONField(default=dict, verbose_name='main_ingredients')),
                ('sub_ingredients', fridge.fields.JSONField(default=dict, verbose_name='sub_ingredients')),
            ],
            options={
                'verbose_name': 'Cooking Menu',
                'ordering': ['menu_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fridge.Menu')),
            ],
            options={
                'verbose_name': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauceName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='sauce',
            field=models.ManyToManyField(related_name='sauce', to='fridge.Sauce'),
        ),
    ]
