# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-22 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_auto_20181222_2029'),
        ('fridge', '0005_fridgeitem_recommendation'),
    ]

    operations = [
    ]
