# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-22 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fridge', '0006_merge_20181223_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scrap_list', models.ManyToManyField(blank=True, related_name='scrap_list', to='fridge.Menu')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='fridge.Menu'),
        ),
    ]
