# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-23 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_auto_20181223_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraplist',
            name='scrap_list',
        ),
        migrations.AddField(
            model_name='scraplist',
            name='scrapinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.Menu'),
        ),
    ]
