# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.CharField(choices=[(0, '자주 거르는 편'), (1, '간단히 먹는 편'), (2, '잘 챙겨 먹는 편')], max_length=100)),
                ('lunch', models.CharField(choices=[(0, '자주 거르는 편'), (1, '간단히 먹는 편'), (2, '잘 챙겨 먹는 편')], max_length=100)),
                ('dinner', models.CharField(choices=[(0, '자주 거르는 편'), (1, '간단히 먹는 편'), (2, '잘 챙겨 먹는 편')], max_length=100)),
                ('pref_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
