# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealpref', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealpref',
            name='dinner',
            field=models.IntegerField(choices=[(0, '자주 거르는 편'), (1, '간단히 먹는 편'), (2, '잘 챙겨 먹는 편')], default=0),
        ),
        migrations.AlterField(
            model_name='mealpref',
            name='lunch',
            field=models.IntegerField(choices=[(0, '자주 거르는 편'), (1, '간단히 먹는 편'), (2, '잘 챙겨 먹는 편')], default=0),
        ),
        migrations.AlterField(
            model_name='mealpref',
            name='morning',
            field=models.IntegerField(choices=[(0, '자주 거르는 편'), (1, '간단히 먹는 편'), (2, '잘 챙겨 먹는 편')], default=0),
        ),
        migrations.AlterField(
            model_name='mealpref',
            name='pref_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
